### ISSUE TITLE
[BUG] [Formatter] pre-commit integration 

### ISSUE THREAD

**Issue by Tirpitz93** [Riverside-Healthcare/djLint#421]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows 10
 - Python Version: Python 3.9.7
 - djLint Version djlint, version 1.18.0
 - template language: jinja/flask

## Issue
pro-commit `files` parameter seems to have no effect:
finds no files to s
```
 - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.18.0
    hooks:
      - id: djlint-jinja
        files: "\\.html"
        args:
          - --reformat
```

```
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
trim trailing whitespace.................................................Passed
check json...........................................(no files to check)Skipped
check for added large files..............................................Passed
djLint for Jinja.....................................(no files to check)Skipped
```

Running this config results in the django config running fine, but the jinja one nothing
```
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.18.0
    hooks:
      - id: djlint-jinja
        files: "\\.html"
        args:
          - --reformat
      - id: djlint-django
        args:
          - --reformat
 ```
results (truncated)
```
...
djLint for Jinja.....................................(no files to check)Skipped
djLint for Django........................................................Failed
...
```

## How To Reproduce

Us the above configurations with pre-commit.

**Comment by christopherpickering** [comment]
Thanks, I will make the docs more clear on this.
By default the `jinja` tag is constrained to `jinja` files types (per "identify", files with .jinja or .j2 extension). 

To override this default, add `types_or: ['html']` to your precommit section for jinja.

Like this:
```yaml
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.18.0
    hooks:
      - id: djlint-jinja
        files: "\\.html"
        types_or: ['html'] <<< here
        args:
          - --reformat
      - id: djlint-django
        args:
          - --reformat
   ```
