### ISSUE TITLE
[FEATURE] pyproject.toml should support list syntax for 

### ISSUE THREAD

**Issue by knyghty** [Riverside-Healthcare/djLint#776]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

Right now you have to specify ignores like this:

```toml
[tool.djlint]
ignore = "H001,H002,H003"
```

More than just being messy, it's also hard to add comments for particular codes. Nicer would be:

```toml
[tool.djlint]
ignore = [
    # Ignored because x.
    "H001", 
    # Ignored because y.
    "H002",
    # Ignored because z.
    "H003",
]
```
